name: wifi_p2p_app
description: "تطبيق الاتصالات المحلي"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # المكتبات الأساسية
  device_info_plus: ^10.1.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  # مكتبة الصوت
  audioplayers: ^6.0.0
  # مكتبة الأذونات (مهمة جداً للواي فاي والموقع)
  permission_handler: ^11.0.0

flutter:
  uses-material-design: true
  
  # 👈 هذا الجزء هو المسؤول عن استيراد ملفات الصوت
  assets:
    - assets/sounds/
